app:
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  github-base-url: ${GITHUB_URL}
  so-base-url: ${SO_URL}

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: optional:.env.properties

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
