app:
  bot:
    url: ${BOT_URL:http://localhost:8080}
  github:
    github-token: ${GITHUB_TOKEN} # env variable
    github-base-url: ${GITHUB_URL:https://api.github.com/repos}
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
    so-base-url: ${SO_URL:https://api.stackexchange.com/2.3}

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: optional:.env.properties

logging:
  structured:
    format:
      console: ecs

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
