app:
  telegram:
    token: ${TELEGRAM_TOKEN} # env variable
  scrapper:
    url: ${SCRAPPER_URL:http://localhost:8081}

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: optional:.env.properties

logging:
  structured:
    format:
      file: ecs
  file:
    name: tg-bot-log.json

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
